import { NextResponse } from 'next/server';
import { db } from '@/lib/db';
import { getSession } from '@/lib/auth';

export async function GET(request){const session=await getSession();if(!session)return NextResponse.json({message:'Unauthorized'},{status:401});try{
 const schoolId=Number(request.cookies.get('schoolhub_school_id')?.value||1);
 if(session.role==='admin'){const [rows]=await db.query(`SELECT s.id_submission,s.assignment_id,s.student_id,s.file_name,s.file_url,s.catatan,s.submitted_at,s.status,u.nama_lengkap AS siswa,c.nama_kelas,a.judul AS tugas,g.id_grade,g.nilai,g.feedback,g.graded_at FROM submissions s JOIN users u ON u.id_user=s.student_id JOIN assignments a ON a.id_assignment=s.assignment_id JOIN classes c ON c.id_class=a.class_id JOIN teacher_classes tc ON tc.class_id=a.class_id AND tc.teacher_id=? LEFT JOIN grades g ON g.id_grade=(SELECT g2.id_grade FROM grades g2 WHERE g2.submission_id=s.id_submission ORDER BY g2.graded_at DESC LIMIT 1) WHERE c.school_id=? ORDER BY s.submitted_at DESC`,[session.id_user,schoolId]);return NextResponse.json({data:rows,role:'admin'});}
 const [rows]=await db.query(`SELECT s.id_submission,a.id_assignment,a.judul AS tugas,a.deskripsi,a.deadline,c.nama_kelas,u.nama_lengkap AS guru,s.file_name,s.file_url,s.submitted_at,s.status,g.nilai,g.feedback,g.graded_at FROM submissions s JOIN assignments a ON a.id_assignment=s.assignment_id JOIN classes c ON c.id_class=a.class_id JOIN users u ON u.id_user=a.teacher_id LEFT JOIN grades g ON g.id_grade=(SELECT g2.id_grade FROM grades g2 WHERE g2.submission_id=s.id_submission ORDER BY g2.graded_at DESC LIMIT 1) WHERE s.student_id=? AND c.school_id=? ORDER BY COALESCE(g.graded_at,s.submitted_at) DESC`,[session.id_user,schoolId]);return NextResponse.json({data:rows,role:'user'});
 }catch(e){return NextResponse.json({message:'Gagal mengambil nilai',error:e.message},{status:500});}}

export async function POST(request){const session=await getSession();if(!session)return NextResponse.json({message:'Unauthorized'},{status:401});if(session.role!=='admin')return NextResponse.json({message:'Forbidden'},{status:403});try{const schoolId=Number(request.cookies.get('schoolhub_school_id')?.value||1); const b=await request.json(),submission_id=Number(b.submission_id),nilai=Number(b.nilai),feedback=String(b.feedback||'').trim();if(!submission_id||Number.isNaN(nilai)||nilai<0||nilai>100)return NextResponse.json({message:'Submission dan nilai 0-100 wajib diisi'},{status:400});const [o]=await db.query('SELECT s.id_submission FROM submissions s JOIN assignments a ON a.id_assignment=s.assignment_id JOIN classes c ON c.id_class=a.class_id WHERE s.id_submission=? AND a.teacher_id=? AND c.school_id=?',[submission_id,session.id_user,schoolId]);if(!o.length)return NextResponse.json({message:'Submission tidak ditemukan'},{status:404});const [e]=await db.query('SELECT id_grade FROM grades WHERE submission_id=? AND teacher_id=? ORDER BY graded_at DESC LIMIT 1',[submission_id,session.id_user]);if(e.length)await db.query('UPDATE grades SET nilai=?,feedback=?,graded_at=NOW() WHERE id_grade=?',[nilai,feedback,e[0].id_grade]);else await db.query('INSERT INTO grades (submission_id,teacher_id,nilai,feedback) VALUES (?,?,?,?)',[submission_id,session.id_user,nilai,feedback]);await db.query("UPDATE submissions SET status='graded' WHERE id_submission=?",[submission_id]);return NextResponse.json({message:'Nilai berhasil disimpan'});}catch(e){return NextResponse.json({message:'Gagal menyimpan nilai',error:e.message},{status:500});}}
