'use client';
import { useEffect,useState } from 'react';
import { PageHeader,Modal,Field,Textarea,FormActions,Notice } from '@/components/admin/Modal';
export default function Grades(){
 const [rows,setRows]=useState([]),[role,setRole]=useState(''),[open,setOpen]=useState(false),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=()=>{setLoading(true);fetch('/api/grades').then(r=>r.json()).then(d=>{if(!d.data)throw Error(d.message);setRows(d.data);setRole(d.role||'')}).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[]);
 const save=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget),r=await fetch('/api/grades',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({submission_id:selected.id_submission,nilai:Number(fd.get('nilai')),feedback:fd.get('feedback')})}),d=await r.json();if(!r.ok)return setError(d.message);setOpen(false);setNotice(d.message);load()};
 if(role==='user')return <div className="space-y-5"><PageHeader title="Nilai Tugas" subtitle="Lihat hasil penilaian dan feedback dari guru."/><Notice text={notice}/><Notice text={error} error/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{loading?<div className="rounded-2xl bg-white p-8 text-center">Memuat...</div>:rows.map(r=><div key={r.id_submission} className="rounded-2xl border border-[#DFEAF7] bg-white p-5 shadow-soft"><div className="flex items-center justify-between"><span className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-bold text-blue-600">{r.nama_kelas}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.nilai!=null?'bg-emerald-50 text-emerald-600':'bg-orange-50 text-orange-600'}`}>{r.nilai!=null?'Dinilai':'Menunggu'}</span></div><h3 className="mt-4 font-extrabold text-[#102A72]">{r.tugas}</h3><div className="mt-1 text-xs text-[#7185AF]">Guru: {r.guru}</div>{r.nilai!=null?<div className="mt-4 flex items-center gap-4"><div className="text-4xl font-extrabold text-[#15449E]">{Number(r.nilai).toFixed(0)}</div><div className="text-xs text-[#6176A8]">Nilai tugas</div></div>:<div className="mt-5 text-sm text-[#7185AF]">Belum ada nilai.</div>}{r.feedback&&<div className="mt-4 rounded-xl bg-[#F6F9FD] p-3 text-sm text-[#6176A8]"><b className="text-[#102A72]">Feedback:</b><br/>{r.feedback}</div>}{r.file_url&&<a href={r.file_url} target="_blank" className="mt-4 inline-block rounded-xl bg-[#F2F6FB] px-4 py-2 text-xs font-bold text-[#486398]">Lihat Pengumpulan</a>}</div>)}{!loading&&!rows.length&&<div className="col-span-full rounded-2xl border border-[#DFEAF7] bg-white p-10 text-center text-sm text-[#7185AF]">Belum ada nilai.</div>}</div></div>;
 return <div className="space-y-5"><PageHeader title="Penilaian Tugas" subtitle="Periksa pengumpulan tugas dan berikan nilai serta feedback."/><Notice text={notice}/><Notice text={error} error/><div className="rounded-2xl border border-[#DFEAF7] bg-white shadow-soft"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead><tr className="border-b border-[#E8EFF7] text-xs uppercase text-[#7185AF]"><th className="px-5 py-4">Siswa</th><th>Kelas</th><th>Tugas</th><th>Pengumpulan</th><th>Nilai</th><th>Status</th><th className="text-right px-5">Aksi</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="p-10 text-center">Memuat...</td></tr>:rows.map(r=><tr key={r.id_submission} className="border-b border-[#F0F4F8] last:border-0"><td className="px-5 py-4 font-bold text-[#102A72]">{r.siswa}</td><td className="text-sm text-[#6176A8]">{r.nama_kelas}</td><td className="text-sm text-[#6176A8]">{r.tugas}</td><td className="text-sm text-[#6176A8]">{new Date(r.submitted_at).toLocaleString('id-ID')}</td><td className="font-extrabold text-blue-600">{r.nilai??'-'}</td><td><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.status==='graded'?'bg-emerald-50 text-emerald-600':'bg-orange-50 text-orange-600'}`}>{r.status==='graded'?'Sudah dinilai':'Perlu diperiksa'}</span></td><td className="px-5 text-right"><button onClick={()=>{setSelected(r);setOpen(true)}} className="rounded-lg bg-blue-50 px-3 py-2 text-xs font-bold text-blue-600">{r.nilai==null?'Beri Nilai':'Edit Nilai'}</button>{r.file_url&&<a target="_blank" href={r.file_url} className="ml-2 rounded-lg bg-[#F2F6FB] px-3 py-2 text-xs font-bold text-[#486398]">File</a>}</td></tr>)}</tbody></table></div></div><Modal open={open} onClose={()=>setOpen(false)} title={`Nilai — ${selected?.siswa||''}`}><form onSubmit={save} className="space-y-4"><Field label="Nilai (0-100)" name="nilai" type="number" min="0" max="100" defaultValue={selected?.nilai??''} required/><Textarea label="Feedback" name="feedback" defaultValue={selected?.feedback||''}/><FormActions onCancel={()=>setOpen(false)} submit="Simpan Nilai"/></form></Modal></div>;
}
